### ISSUE TITLE
Consider having functionality separate into multiple contracts

### ISSUE THREAD

**Issue by maurolacy** [babylonlabs-io/babylon-contract#11]
**[<img src="https://avatars.githubusercontent.com/u/11656534?s=17&v=4" width="17" height="17"> @maurolacy](https://www.github.com/maurolacy)** cloned issue [babylonchain/babylon-contract#131](https://www.github.com/babylonchain/babylon-contract/issues/131) on 2024-06-05: 

> Related to #130.
> 
> 
> 
> `btc-staking` is growing big, and is in fact containing functionality related to finality signatures, and the finality providers set.
> 
> 
> 
> Consider introducing a new `finality` contract to handle finality votes, power, and the voting round. The power that comes from`btc-staking` can be read through a raw query for performance.
> 
> 
> 
> See the `poe-contracts` (https://www.github.com/confio/poe-contracts) design / structure for reference / ideas.
> 
> 
> 
> Also, the voting round and the finality validator set, though related to finality, could be perhaps better be in its own `fpset` contract. Again, `poe-contracts` provides a reference for this.

**Comment by SebastianElvis** [comment]
Subsumed by #52 and #53
