### ISSUE TITLE
OP: integration test vs. unit test

### ISSUE THREAD

**Issue by maurolacy** [babylonlabs-io/babylon-contract#18]
**[<img src="https://avatars.githubusercontent.com/u/111917526?s=17&v=4" width="17" height="17"> @bap2pecs](https://www.github.com/bap2pecs)** cloned issue [babylonchain/babylon-contract#175](https://www.github.com/babylonchain/babylon-contract/issues/175) on 2024-06-19: 

> ## Context
> 
> 
> 
> I see `babylon` and `btc-staking` contracts both use integration tests like
> 
> 
> 
> ```
> 
> // need to add dep `cosmwasm_vm`
> 
> static WASM: &[u8] = include_bytes!("../../../artifacts/my_contract.wasm");
> 
> 
> 
> #[test]
> 
> fn proper_initialization() {
> 
>   let mut deps = mock_instance(WASM, &[]);
> 
> 」
> 
> ```
> 
> 
> 
> why not just use unit test which is simpler and does not depend on the binary?
> 
> 
> 
> ```
> 
> #[test]
> 
> fn proper_initialization() {
> 
>   let mut deps = mock_dependencies();
> 
> }
> 
> ```
> 
> 
> 
> cc @maurolacy @SebastianElvis
> 
> 
> 
> ## Tasks
> 
> 
> 
> - [ ] decide the missing integration/uint tests
> 
> - [ ] implement those tests

**Comment by SebastianElvis** [comment]
@bap2pecs is this sill relevant?

**Comment by bap2pecs** [comment]
we can close it
