### ISSUE TITLE
sdk: instantiate all Babylon contracts using Babylon SDK

### ISSUE THREAD

**Issue by SebastianElvis** [babylonlabs-io/babylon-contract#67]
It would be good to let Babylon SDK 's `x/babylon` module to instantiate all Babylon contracts. This

- simplifies the BTC staking integration as one does not need a gov prop to set contract addresses in module params
- avoids contracts instantiating each other

**Comment by maurolacy** [comment]
Duplicate / sibling of https://github.com/babylonlabs-io/babylon-sdk/issues/45.

**Comment by SebastianElvis** [comment]
Oops lets follow https://github.com/babylonlabs-io/babylon-sdk/issues/45 then
